name: a1_notation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        run: rustup component add rustfmt clippy

      - name: Run Lint and Tests
        run: |
          cargo clippy -- -D warnings
          cargo fmt --all -- --check
          cargo test
